export const ADD_TASK_REQUEST="ADD_TASK_REQUEST"
export const ADD_TASK_SUCCESSS="ADD_TASK_SUCCESSS"
export const ADD_TASK_FAILURE="ADD_TASK_FAILURE"

export const GET_TASK_REQUEST="GET_TASK_REQUEST"
export const GET_TASK_SUCCESSS="GET_TASK_SUCCESSS"
export const GET_TASK_FAILURE="GET_TASK_FAILURE"

export const SINGLE_TASK_REQUEST="SINGLE_TASK_REQUEST"
export const SINGLE_TASK_SUCCESSS="SINGLE_TASK_SUCCESSS"
export const SINGLE_TASK_FAILURE="SINGLE_TASK_FAILURE"

export const UPDATE_TASK_REQUEST="UPDATE_TASK_REQUEST"
export const UPDATE_TASK_SUCCESSS="UPDATE_TASK_SUCCESSS"
export const UPDATE_TASK_FAILURE="UPDATE_TASK_FAILURE"

export const DELETE_TASK_REQUEST="DELETE_TASK_REQUEST"
export const DELETE_TASK_SUCCESSS="DELETE_TASK_SUCCESSS"
export const DELETE_TASK_FAILURE="DELETE_TASK_FAILURE"

export const ALL_TASK_REQUEST="ALL_TASK_REQUEST"
export const ALL_TASK_SUCCESSS="ALL_TASK_SUCCESSS"
export const ALL_TASK_FAILURE="ALL_TASK_FAILURE"